### ISSUE TITLE
data cube mix error

### ISSUE THREAD

**Issue by danielcsant** [Stratio/Sparkta#1055]
When running a policy with two cubes:
1 -> price, client, ts, count
2 -> price, ts, sum

Values in operators are mixed randomly.

Seing in the demo

**Comment by arinconstrio** [comment]
find dimension by name, or update state by key repartition

**Comment by Gschiavon** [comment]
I couldn't reproduce this error, but we have to pay attention to see if occurs again.

**Comment by danielcsant** [comment]
Issue migrated to JIRA.
