### ISSUE TITLE
if jq is not installed, sparkta will not be able to install from deb

### ISSUE THREAD

**Issue by antonioalf** [Stratio/Sparkta#1152]
~/workspace/sparkta$ sudo dpkg -i dist/target/stratio-sparkta-0.6.2-RC4-SNAPSHOT.all.deb
dpkg: acerca de .../stratio-sparkta-0.6.2-RC4-SNAPSHOT.all.deb que contiene stratio-sparkta, problema de predependencia:
 stratio-sparkta predepende de jq
  jq no está instalado.

dpkg: error al procesar el archivo dist/target/stratio-sparkta-0.6.2-RC4-SNAPSHOT.all.deb (--install):
 problema de predependencia - no se instala stratio-sparkta
Se encontraron errores al procesar:
 dist/target/stratio-sparkta-0.6.2-RC4-SNAPSHOT.all.deb

**Comment by danielcsant** [comment]
With apt-get this error does not appear

**Comment by danielcsant** [comment]
Issue migrated to JIRA.
