### ISSUE TITLE
Failure vagrant up 

### ISSUE THREAD

**Issue by hrsoto** [Stratio/sparkta#152]
When I execute vagrant up, an error occurs:

A host only network interface you're attempting to configure via DHCP
already has a conflicting host only adapter with DHCP enabled. The
DHCP on this adapter is incompatible with the DHCP settings. Two
host only network interfaces are not allowed to overlap, and each
host only network interface can have only one DHCP server. Please
reconfigure your host only network or remove the virtual machine
using the other host only network.

Thanks for all :D

**Comment by Brezyll** [comment]
Hi hrsoto, 

this seems to be a conflict with VirtualBox, make sure you have the latest version of both and then check out this web site https://github.com/mitchellh/vagrant/issues/3083 where they solve the same problem.

Regards.

**Comment by dmorales-stratio** [comment]
Deleting all conflicting network interfaces in VirtualBox should fix this issue.

Open VB > General Setup > Network > Tab "Host-only interfaces".
