### ISSUE TITLE
Installation in batch mode / via Juju

### ISSUE THREAD

**Issue by SaMnCo** [Stratio/sparkta#159]
Hey, 
I've been working on a new installation procedure using Ubuntu Juju. I wrote 2 charms (admin/agent) for the platform in order to test. 
* https://github.com/SaMnCo/charm-stratio-node
* https://github.com/SaMnCo/charm-stratio-admin

The idea is to avoid the server-side SSH connection with a password, but rather auto install from the node. The server is authorized to expose variables and to act on his side. 

I have all ports opened, I download the bootstrap to install chef-client, I manage to get the validation.pem & dbkey to start the install. 
So I get to the point where the server and the nodes are all functional. The GUI sees my nodes. But there is no communication between the 2 of them (monitoring doesn't work, actions like start/stop do not work either. 

Since the admin side is not on GitHub, can you tell me exactly 
* What happens when one adds nodes manually in the GUI on the server side? 
* How do you send commands from the GUI to the nodes? 

BTW the documention doesn't mention the following ports: 
PORT_MONGO_STORAGE=27017
PORT_ELASTIC_MNGT=9200
PORT_ELASTIC_STORAGE=9300

BTW2, I sent an email to contact@stratio.com to ask how I could help you as I like your project. Didn't get an answer yet. Any hints? 

Thanks in advance, any help appreciated.

**Comment by dmorales-stratio** [comment]
Hi, thanks for your feedback.

Since your issue is related to Stratio Admin, please contact with the Stratio Admin team by using Jira

https://stratio.atlassian.net/secure/Dashboard.jspa

They will take care about your questions. Anyway, i am going to forward them your question.

I do not manage contact account, so let me find and answer your email.

**Comment by SaMnCo** [comment]
Cool! 
Thx for managing the question. I tried connecting to your link but not having a Jira account locks me out of it. 
Happy to have one opened and restart from there if it's best practice. Just let me know

**Comment by dmorales-stratio** [comment]
Just register yourself at Jira Cloud and open the issue, the Admin team will be glad to help you.

(i am already checking out your email at contact)

**Comment by SaMnCo** [comment]
OK let me know when my address is validated, I created a Atlassian Cloud
account with this email address (samnco@gmail.com)

Thanks for your help,
Best,
Samuel

2015-05-18 11:47 GMT+02:00 David Morales <notifications@github.com>:

> Just register yourself at Jira Cloud and open the issue, the Admin team
> will be glad to help you.
>
> (i am already checking out your email at contact)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/sparkta/issues/159#issuecomment-102998218>.
>



-- 
SaM'n'Co
R'U Ready? I was BORN ready!

**Comment by dmorales-stratio** [comment]
Ok, thanks.

**Comment by dmorales-stratio** [comment]
Sorry, forget about the jira issue.  Use this group instead 

https://groups.google.com/forum/?hl=es#!forum/stratio-admin


Thanks

**Comment by SaMnCo** [comment]
OK no problem. I requested access.

Many thanks for following up,
Best,
Samuel

2015-05-19 15:20 GMT+02:00 David Morales <notifications@github.com>:

> Sorry, forget about the jira issue. Use this group instead
>
> https://groups.google.com/forum/?hl=es#!forum/stratio-admin
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/sparkta/issues/159#issuecomment-103486178>.
>



-- 
SaM'n'Co
R'U Ready? I was BORN ready!
