### ISSUE TITLE
missing documentation for deb and rpm package generation

### ISSUE THREAD

**Issue by elenapascual** [Stratio/sparkta#185]
Hi,
I tried to install sparkta and I found myself struggling a bit when it came to package. It didn't generate .deb and .rpm packages with the common command "mvn package". 
What am I missing?

Thanks

**Comment by arinconstrio** [comment]
Hi,
Maybe you need install a package in your PC
You can take a look on this issue
https://github.com/Stratio/unix-maven-plugin/issues/15

**Comment by elenapascual** [comment]
Thanks for the rapid answer. It was a good lead.

I found the solution to my problem. I took a look to pom.xml and discovered the profile section for those packages. I then typed: 
      -  "mvn package -Ppackage" and it worked.

Regarding the missing tools for deb and rpm as I work on Linux Mint I only needed to install rpmbuild. 

Thank you!

**Comment by danielcsant** [comment]
closed with Issue #186
