### ISSUE TITLE
Update to spark 1.4.1

### ISSUE THREAD

**Issue by dmorales-stratio** [Stratio/sparkta#446]

**Comment by sgomezg** [comment]
There is a problem with Spark 1.4.1. Sparks has changed ```TestSuiteBase```, using new Trait (```SparkFunSuite```) contained in spark-core -only for tests.

**Comment by gserranojc** [comment]
If ours Datasources not support this Spark version we can't update the project.

**Comment by sgomezg** [comment]
The missing dependency was spark-core_2.10-tests
