### ISSUE TITLE
If fragmentType and/or name are not specified when deleting a fragment incorrect error shown

### ISSUE THREAD

**Issue by antonioalf** [Stratio/sparkta#508]
If fragmentType and/or name are not specified when deleting a fragment, the error shown is very misleading:

Response Code: 405
Response Message: Method Not Allowed
Response Body: HTTP method not allowed, supported methods: GET

A check should be included to make sure that those values are not empty.

If we try these kind of operations directly in swagger UI, it will sty in a loop without showing anything

**Comment by anistal** [comment]
The endpoint used to delete a fragment is DELETE /type/name. 

There is not any endpoint such as DELETE /name. Therefore spray returns with a 405 (Method Not Allowed) and searches with the best option that fits with it: in this case a GET request.

Closed as invalid.
