### ISSUE TITLE
Index created in Solr automatically, only for local filesystem

### ISSUE THREAD

**Issue by raulsaeztapia** [Stratio/sparkta#743]
At create an index on Cloudera Search (Solr Cloud over Cloudera HDFS) I have configured my policy as:
```
...
  "cubes": [
    {
      "name": "items",
      "checkpointConfig": {
        "timeDimension": "minute",
        "granularity": "minute",
        "interval": 30000,
        "timeAvailability": 60000
      },
      "dimensions": [
        {
          "name": "smfProcess",
          "field": "smfProcess"
        },
        {
          "name": "timestampMinute",
          "field": "creationDate",
          "type": "DateTime",
          "precision": "minute"
        }
      ],
      "operators": [
        {
          "name": "count-operator",
          "type": "Count",
          "configuration": {}
        }
      ]
    }
  ],
...
...
  "outputs": [
    {
      "name": "out-solr",
      "type": "Solr",
      "configuration": {
        "connection": "node5.stratio.com:2181/solr",
        "createSchema": "true",
        "isCloud": "true",
        "cloudDataDir": "smf-agg-proc-minute/data",
        "fixedAggregation": "_indexed_at_tdt:0"
      }
    }
  ]
```

When publishing process has finished I review how was my collections on Solr and this is the result:

**Instance:** `/var/lib/solr/smf-agg-proc-minute/data/id_smfProcess_timestampMinute_minute`
**Data:** `/var/lib/solr/smf-agg-proc-minute/data/id_smfProcess_timestampMinute_minute/smf-agg-proc-minute/data/id_smfProcess_timestampMinute_minute/data`
**Index:** `/var/lib/solr/smf-agg-proc-minute/data/id_smfProcess_timestampMinute_minute/smf-agg-proc-minute/data/id_smfProcess_timestampMinute_minute/data/index`

That would like to me is a **cloud generation of indexes over HDFS**.

Version of Solr:
*solr-spec 4.10.3*
*solr-impl 4.10.3-cdh5.4.3 exported - jenkins - 2015-06-24 19:42:36*
*lucene-spec 4.10.3*
*lucene-impl 4.10.3-cdh5.4.3 exported - jenkins - 2015-06-24 19:32:31*

**Comment by sgomezg** [comment]
Solved: #998
